version: '2'
services:
    throttlingservice-app:
        image: throttlingservice
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://throttlingservice-postgresql:5432/throttlingService
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    throttlingservice-postgresql:
        extends:
            file: postgresql.yml
            service: throttlingservice-postgresql
